# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/blackgolyb/Documents/PyMage/ui/image_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_imageEditor(object):
    def setupUi(self, imageEditor):
        imageEditor.setObjectName("imageEditor")
        imageEditor.resize(144, 443)

        self.retranslateUi(imageEditor)
        QtCore.QMetaObject.connectSlotsByName(imageEditor)

    def retranslateUi(self, imageEditor):
        _translate = QtCore.QCoreApplication.translate
        imageEditor.setWindowTitle(_translate("imageEditor", "ScrollArea"))
