# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/blackgolyb/Documents/PyMage/ui/marge_images.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(140, 120)
        Form.setMinimumSize(QtCore.QSize(140, 120))
        Form.setAutoFillBackground(False)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(-1, 6, 6, 6)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.margeTypeSelect = QtWidgets.QComboBox(self.groupBox_2)
        self.margeTypeSelect.setObjectName("margeTypeSelect")
        self.margeTypeSelect.addItem("")
        self.margeTypeSelect.addItem("")
        self.margeTypeSelect.addItem("")
        self.margeTypeSelect.addItem("")
        self.margeTypeSelect.addItem("")
        self.verticalLayout_3.addWidget(self.margeTypeSelect)
        self.margeImagesBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.margeImagesBtn.setEnabled(True)
        self.margeImagesBtn.setObjectName("margeImagesBtn")
        self.verticalLayout_3.addWidget(self.margeImagesBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Marge images"))
        self.margeTypeSelect.setItemText(0, _translate("Form", "Lab"))
        self.margeTypeSelect.setItemText(1, _translate("Form", "RGB"))
        self.margeTypeSelect.setItemText(2, _translate("Form", "HSV"))
        self.margeTypeSelect.setItemText(3, _translate("Form", "XYZ"))
        self.margeTypeSelect.setItemText(4, _translate("Form", "YIQ"))
        self.margeImagesBtn.setText(_translate("Form", "Marge images"))
