# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/blackgolyb/Documents/PyMage/ui/mask_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(732, 449)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.view_layout = QtWidgets.QVBoxLayout(self.groupBox)
        self.view_layout.setObjectName("view_layout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RectBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.RectBtn.setObjectName("RectBtn")
        self.horizontalLayout_2.addWidget(self.RectBtn)
        self.ElipseBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.ElipseBtn.setObjectName("ElipseBtn")
        self.horizontalLayout_2.addWidget(self.ElipseBtn)
        self.RectBrushBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.RectBrushBtn.setObjectName("RectBrushBtn")
        self.horizontalLayout_2.addWidget(self.RectBrushBtn)
        self.CircleBrushBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.CircleBrushBtn.setObjectName("CircleBrushBtn")
        self.horizontalLayout_2.addWidget(self.CircleBrushBtn)
        self.DrawOrErase = QtWidgets.QCheckBox(self.groupBox_4)
        self.DrawOrErase.setObjectName("DrawOrErase")
        self.horizontalLayout_2.addWidget(self.DrawOrErase)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.view_layout.addWidget(self.groupBox_4)
        self.editorView = QtWidgets.QGraphicsView(self.groupBox)
        self.editorView.setObjectName("editorView")
        self.view_layout.addWidget(self.editorView)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.maskList = QtWidgets.QListWidget(self.groupBox_3)
        self.maskList.setObjectName("maskList")
        self.verticalLayout.addWidget(self.maskList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.newMaskBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.newMaskBtn.setObjectName("newMaskBtn")
        self.horizontalLayout.addWidget(self.newMaskBtn)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.nameEditor = QtWidgets.QLineEdit(self.groupBox_2)
        self.nameEditor.setObjectName("nameEditor")
        self.verticalLayout_4.addWidget(self.nameEditor)
        self.saveMaskBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.saveMaskBtn.setObjectName("saveMaskBtn")
        self.verticalLayout_4.addWidget(self.saveMaskBtn)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "View"))
        self.groupBox_4.setTitle(_translate("Form", "GroupBox"))
        self.RectBtn.setText(_translate("Form", "Rect"))
        self.ElipseBtn.setText(_translate("Form", "Elipse"))
        self.RectBrushBtn.setText(_translate("Form", "Rect brush"))
        self.CircleBrushBtn.setText(_translate("Form", "Circle brush"))
        self.DrawOrErase.setText(_translate("Form", "Draw or eraese"))
        self.groupBox_3.setTitle(_translate("Form", "Control"))
        self.newMaskBtn.setText(_translate("Form", "New Mask"))
        self.groupBox_2.setTitle(_translate("Form", "Settings"))
        self.label.setText(_translate("Form", "name"))
        self.saveMaskBtn.setText(_translate("Form", "Save mask"))
